version: '3.8'

services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: family_actual_budget
    ports:
      - "5006:5006"
    volumes:
      - ./actual-data:/data
    environment:
      - ACTUAL_PORT=5006
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5006/" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  actual-data:
